In [1]:
import numpy as np
!pip install numpy
a =np.array([2,4,6,8])
a


array([2, 4, 6, 8])

In [2]:
type(a) #checking of type

numpy.ndarray

In [3]:
a.dtype #numerical type of elements

dtype('int64')

In [4]:
#number of dimension
a.ndim

1

In [5]:
a.shape #shape of array

(4,)

In [6]:
a.itemsize #bytes per element

8

In [7]:
#bytes of memory used
a.nbytes

32

In [8]:
#multidimension array
a=np.array([[3,4,5,6],[1,2,7,9]])
a

array([[3, 4, 5, 6],
       [1, 2, 7, 9]])

In [9]:
a.dtype #data type

dtype('int64')

In [10]:
a.shape #shape=rows,coloums

(2, 4)

In [11]:
a.size #element count

8

In [12]:
a.ndim # number dimension

2

In [14]:
#get/set elements
a[1,1]
a[1,1]=10
a

array([[ 3,  4,  5,  6],
       [ 1, 10,  7,  9]])

In [16]:
#represent particular row using single index
a[1]



array([ 1, 10,  7,  9])

In [20]:
import numpy as np #version of array
print(np.__version__)

2.3.5


In [21]:
#zero dimension
import numpy as np
arr = np.array(2)
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

2
1
()
<class 'numpy.ndarray'>
number of dimensions: 0


In [25]:
import numpy as np
arr = np.array([2])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

[2]
1
(1,)
<class 'numpy.ndarray'>
number of dimensions: 1


In [24]:
import numpy as np
arr = np.array([2,2,3,3,45,5,5])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

[ 2  2  3  3 45  5  5]
7
(7,)
<class 'numpy.ndarray'>
number of dimensions: 1


In [26]:
import numpy as np
arr = np.array([[2],[3]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)



[[2]
 [3]]
2
(2, 1)
<class 'numpy.ndarray'>
number of dimensions: 2


In [27]:
import numpy as np
arr = np.array([[2],[7,7]]) #number of coloum in each row should be same otherwise value error
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [36]:
import numpy as np
arr = np.array([[2,3,4],[5,6,7],[8,1,9]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

[[2 3 4]
 [5 6 7]
 [8 1 9]]
9
(3, 3)
<class 'numpy.ndarray'>
number of dimensions: 2


In [37]:
arr.dtype

dtype('int64')

In [30]:
import numpy as np
arr = np.array([[2.5,3.4],[4.4,6.6]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

[[2.5 3.4]
 [4.4 6.6]]
4
(2, 2)
<class 'numpy.ndarray'>
number of dimensions: 2


In [32]:
arr.dtype

dtype('float64')

In [33]:
import numpy as np
arr = np.array([[2.5,3],[4,6.6]]) #array can hold same set of elements by coverting int into float
print(arr)                            # implicit conversion i,e integer is convert into float
print(arr.size)
print(arr.shape)
print(type(arr))
nd = arr.ndim
print('number of dimensions:',nd)

[[2.5 3. ]
 [4.  6.6]]
4
(2, 2)
<class 'numpy.ndarray'>
number of dimensions: 2


In [34]:
arr.dtype

dtype('float64')

In [43]:
#create an array with 5 dimension and 
# verify that it has 5 dimensions
import numpy as np
arr = np.array ([1,2,3,4],ndmin=5) #ndmin for  creating dimension
print(arr)
print("dimension is :",arr.ndim) #ndim for geting dimension


[[[[[1 2 3 4]]]]]
dimension is : 5


In [45]:
#array indexing 
#get the first element from the following array
import numpy as np
arr=np.array([1,2,3,4]) #index 0,1,2,3,....
print(arr[2])

3


In [52]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5]]) #index 0,1,2,3,....
print(arr[1,0])

3


In [56]:
#write a program to calculate the sum of third and fourth element from the array
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [58]:
#create a two dim array i.e 2*5 ,acess the second element on 1st dim
import numpy as np
arr = np.array([[2,3,4,5,6],[1,7,8,9,10]])
print("second element :", arr[0,1])

second element : 3


In [60]:
print("third element :", arr[1,2]) #third element of second dimension

third element : 8


In [65]:
#access  the third element of second array of the first array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[21,43,54]]])
print(arr[0,1,2])

6


In [66]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[21,43,54]]])
print(arr[1,1,2])

54


In [77]:
#python program to perform basic arithmatic operations
#using 1-D array
import numpy as np
arr = np.array([1,2,3,5,6,7,8,9])
sum=arr[0]+arr[2]
diff = arr[3]-arr[2]
product=arr[1]*arr[3]
div =arr[5]/arr[6]
print("sum :",sum)
print("difference:",diff)
print("product :", product)
print("division:",div)

sum : 4
difference: 2
product : 10
division: 0.875


In [78]:
import numpy as np
arr = np.array([1,2,3,5,6,7,8,9])
print(arr[3:5])
print(arr[:8])
print(arr[0:])
print(arr[-7:-1])
print(arr[:-7])
print(arr[-7:])
print(arr[-1:])

[5 6]
[1 2 3 5 6 7 8 9]
[1 2 3 5 6 7 8 9]
[2 3 5 6 7 8]
[1]
[2 3 5 6 7 8 9]
[9]


In [79]:
#slicing 2D array
import numpy as np
arr =np.array([[1,2,3,5],[12,34,56,78]])
print(arr)
print(arr[1,1:3])


[[ 1  2  3  5]
 [12 34 56 78]]
[34 56]


In [80]:
import numpy as np
arr =np.array([[1,2,3,5],[12,34,56,78]])  # for both elemnt indrx 2:
print(arr)
print(arr[0:2,2])


[[ 1  2  3  5]
 [12 34 56 78]]
[ 3 56]


In [81]:
import numpy as np
arr =np.array([[1,2,3,5],[12,34,56,78]])
print(arr)
print(arr[0:2,1:4])


[[ 1  2  3  5]
 [12 34 56 78]]
[[ 2  3  5]
 [34 56 78]]


In [82]:
# nupy array copy
import numpy as np
arr = np.array([1,2,3,5,6,7,8,9])
x = arr.copy()
print(arr)
print(x)

[1 2 3 5 6 7 8 9]
[1 2 3 5 6 7 8 9]


In [83]:
import numpy as np
arr = np.array([1,2,3,5,6,7,8,9])
x = arr.copy()
arr[3]=23
print(arr)
print(x)

[ 1  2  3 23  6  7  8  9]
[1 2 3 5 6 7 8 9]


In [84]:
import numpy as np
arr = np.array([1,2,3,5,6,7,8,9])
x = arr
arr[0]=23
print(arr)
print(x)

[23  2  3  5  6  7  8  9]
[23  2  3  5  6  7  8  9]


In [88]:
#create a one dimensuion array with 12 elements and covert that into 2D array with 4*3 elements
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(1,2)
print(arr)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (1,2)

In [86]:
#create a one dimensuion array with 12 elements and covert that into 3D array with 4*3 elements
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [89]:
#numpy arange function
import numpy as np
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
import numpy as np
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [93]:
#element wise arithmetic operations
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1 +arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2)              

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [94]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
concatenated_arr =np.concatenate((arr1,arr2),axis=0) #for adding row wise
print(concatenated_arr)
print()
concatenated_arr =np.concatenate((arr1,arr2),axis=1) #for adding column wise
print(concatenated_arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [98]:
arr1=np.array([[1,2,5],[3,4,7]])
print(arr1)
print(arr1.shape)
transposed_arr1=arr1.transpose() #rows changed columns and vice versa
print(transposed_arr1)
print(transposed_arr1.shape) #shape get reversed
flattened_arr1=arr1.flatten() #represent matrics in single row
print(flattened_arr1)

[[1 2 5]
 [3 4 7]]
(2, 3)
[[1 3]
 [2 4]
 [5 7]]
(3, 2)
[1 2 5 3 4 7]


In [99]:
import numpy as np
a = np.array([1+1j,1+0j,4.5,3,2,2j])
print(a)
print("checking for complex number:") #checking for the complex number
print(np.iscomplex(a))
print("checking for real number:") #checking for the real number
print(np.isreal(a))
print("checking for scalar:")
print(np.isscalar(3)) #this give for scalar value
print(np.isscalar([3])) #[]this represent list(group of elements)

[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking for complex number:
[ True False False False False  True]
checking for real number:
[False  True  True  True  True False]
checking for scalar:
True
False


In [101]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [102]:
arr=np.zeros(0)
arr

array([], dtype=float64)

In [105]:
arr=np.zeros((2,3)) #give zeros in float form
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
one=np.ones((2,4)) # give ones in float form
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
empty1=np.empty((4,3)) #this give different and multiple value once go on exicuting
empty1

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323],
       [4.9e-323, 5.4e-323, 5.9e-323]])

In [26]:
import numpy as np
crop_yield=np.array([
    [2,3,4,5],
    [1,12,34,56],
    [32,43,54,65],
    [22,33,44,76]
   ])


print(crop_yield)
print(f'\n data type:{crop_yield.dtype}')
print(f'shape:{crop_yield.shape}')
print(f'total elements:{crop_yield.size}')
print(f'number of dimension:{crop_yield.ndim}')

    

TypeError: 'tuple' object is not callable

In [24]:
(2+3+4+5)/4

3.5

In [7]:
total_yield=np.sum(crop_yield)
avg_yield_per_farm = np.mean(crop_yield,axis=1)
avg_yield_per_season= np.mean(crop_yield,axis=0)
max_yield = np.max(crop_yield)
min_yield = np.min(crop_yield)
print("total production:",total_yield)
print("avg yield axis =1:",avg_yield_per_farm)
print("avg yield axis =0:",avg_yield_per_season)
print("maximum yield:",max_yield)
print("minimum yield:",min_yield)

total production: 486
avg yield axis =1: [ 3.5  25.75 48.5  43.75]
avg yield axis =0: [14.25 22.75 34.   50.5 ]
maximum yield: 76
minimum yield: 1


In [8]:
max_yield = np.max(crop_yield,axis=1)
min_yield = np.min(crop_yield,axis=0)
print("maximum yield:",max_yield)
print("minimum yield:",min_yield)

maximum yield: [ 5 56 65 76]
minimum yield: [1 3 4 5]


In [9]:
max_yield = np.max(crop_yield,axis=0)
min_yield = np.min(crop_yield,axis=1)
print("maximum yield:",max_yield)
print("minimum yield:",min_yield)

maximum yield: [32 43 54 76]
minimum yield: [ 2  1 32 22]


In [11]:
best_farm=np.argmax(avg_yield_per_farm)
print("\nbest performing farm:farm",best_farm+1)
print("thier average yield:",round(avg_yield_per_farm[best_farm],2),"tons")


best performing farm:farm 3
thier average yield: 48.5 tons


In [12]:
max_yield = np.max(crop_yield) #incase of not mentioning axis it give overall considering
min_yield = np.min(crop_yield)
print("maximum yield:",max_yield)
print("minimum yield:",min_yield)

maximum yield: 76
minimum yield: 1


In [13]:
median_yield=np.median(crop_yield)
print("median:",median_yield)

median: 32.5


In [16]:
std_yield=np.std(crop_yield)
print=("std dev:",std_yield)

In [29]:
#boolen indexing:find exceptional yields
import numpy as np
crop_yield=np.array([
    [2,3,4,5],
    [1,12,34,56],
    [32,43,54,65],
    [22,33,44,76]
   ])
print(crop_yield)
exceptional =crop_yield>34
print(exceptional)
print("\n exceptional  yields(>34):")
print(crop_yield[exceptional])

TypeError: 'tuple' object is not callable